### ISSUE TITLE
Include Build/Install instructions in a Readme

### ISSUE THREAD

**Issue by Zeustopher** [collinss/sticky#1]
I'd love to try this project out and give feedback for it, but I don't know where to begin on building it, installing it, etc.

If you could write a quick summary here in this issue I'd be happy to formalize it a little bit into a `README.md` file.

**Comment by 4Syno** [comment]
I had the same question :) Here is my walkthrough:
Start from your home drive :~$ 

```
mkdir Apps
cd Apps
git clone https://github.com/collinss/sticky.git
git clone https://github.com/tsaarni/docker-deb-builder.git
cd docker-deb-builder
docker build -t docker-deb-builder:20.04 -f Dockerfile-ubuntu-20.04 .
```

This process take a moment and will finish with the docker image: 
Successfully built xxxxxxxxx
Successfully tagged docker-deb-builder:20.04

```
mkdir output
./build -i docker-deb-builder:20.04 -o output ~/Apps/sticky
```
After successful build you will find the sticky_0.0.1_all.deb file in output directory.

To install prepare the dependencies if needed:
`sudo apt install gir1.2-xapp-1.0 gir1.2-gspell-1`

```
cd output
sudo dpkg -i sticky_0.0.1_all.deb
```

If you are not familiar with docker check out this article: https://unix.stackexchange.com/questions/117503/how-to-compile-a-debian-package-from-source
pretty the same, more old school ;)

**Comment by collinss** [comment]
I just added a readme with instructions on how to build/install.

**Comment by yochananmarqos** [comment]
I'm pretty sure there's a typo [here](https://github.com/collinss/sticky/blob/master/README.md#otherwise-and-this-is-valid-anywhere-if-you-want-to-avoid-packaging).

`usr/sticky.desktop` doesn't exist. Even if it did, the rest of the files weren't copied and it wouldn't do anything. ;)
```
sudo cp -r usr/sticky.desktop /usr/
```

Should be

```
sudo cp -r  usr /usr/
```

**Comment by collinss** [comment]
Good catch. Looks like I misplaced my cursor while I was typing in the file name. It should have been on the line below.
